test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2a54cd03.name = "Upgrade from 4.10.0"

    test_upgrade_from.1e360398.name = "Upgrade from 4.12.0"
